### ISSUE TITLE
License - GPL and App Store

### ISSUE THREAD

**Issue by colincameron** [is0bnd/PNGScissors#1]
The license for this library in GitHub is GPL, which [isn't compatible with the App Store](https://www.engadget.com/2011-01-09-the-gpl-the-app-store-and-you.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAL-LIwOV-rVIOp_9xt4CiLSzzbjFeuOIbYG6IQL-v9JCmI_7ngIeFD5A9TCRPnFhpLFB1heI1kzGZGANgzi8a-j3y_RUMBfoSmPVFGafbFGp8twi1iZaCSGi0krmhw0MAq4bIEbfmL2ziJgkqlLdpQ1OSO4_REe43U16spcVxqHH).

However, on [your CocoaPods listing](https://cocoapods.org/pods/PNGScissors), the license is stated as MIT.

Since this library is a derivative work of pngquant, which is licensed under the GPL, you cannot license your code under the MIT license. The CocoaPods listing is misleading, illegal, and could land developers who use your code in a lot of trouble for including GPL code (the pngquant code) in their app.

Please consider removing this library from CocoaPods, or at least updating the listing to correct the license, and including a warning that it is not App Store compatible.

**Comment by is0bnd** [comment]
I changed MIT to GPL
